### ISSUE TITLE
[main] main-banner

### ISSUE THREAD

**Issue by jh1109** [likelion-lab8-JS/market-karly#18]
## 🌳 작업 브랜치
- page_main

## 📋 TASK 개요
- main page 내 main-banner 완성하기

## ✅ To Do 및 진행상황
- [x] swiper 마크업
- [x] swiper 레이아웃 및 버튼 커스텀
- [x] swiper 버튼 위치 조정
- [x] banner 이미지 반응형 확인
- [x] pagnation 추가, 레이아웃 및 디자인
- [x] swiper 기능 추가
