### ISSUE TITLE
[cart] 장바구니 마크업하기

### ISSUE THREAD

**Issue by hayeonn2** [likelion-lab8-JS/market-karly#20]
## 🌳 작업 브랜치
page_cart

## 📋 TASK 개요
장바구니 부분 마크업을 합니다.

## ✅ To Do 및 진행상황
- [x] 장바구니 아코디언 메뉴 만들기
- [x] 장바구니 아코디언 메뉴 css 작업하기
- [x] 배송지와 상품금액 칸 HTML 마크업하기
- [x] 배송지와 상품금액 칸 css 작업하기
