### ISSUE TITLE
[main] 상품 추천

### ISSUE THREAD

**Issue by jh1109** [likelion-lab8-JS/market-karly#21]
## 🌳 작업 브랜치
- page_main

## 📋 TASK 개요
- 오늘의 상품 추천과 세일 상품 추천 완성하기

## ✅ To Do 및 진행상황
- [x] swiper 마크업
- [x] swiper 레이아웃 : prev,next 버튼 커스텀
- [x] 처음과 끝 슬라이드에서는 한개의 버튼만 보이게 하기
- [x] prev, next 버튼을 누르면 4개 단위 다음 슬라이드로 이동
- [x] 세일 상품 추천 section도 동일하게 만들기
