### ISSUE TITLE
[Detail] 상품문의 > 마크업

### ISSUE THREAD

**Issue by DoctorK4** [likelion-lab8-JS/market-karly#22]
## 🌳 작업 브랜치
page_productDetail_dongryul

## 📋 TASK 개요
상품문의 파트의 아코디언 메뉴 등을 마크업 + css로 구현한다. 

## ✅ To Do 및 진행상황
- [x] 상품문의 파트 마크업
- [x] 상품문의 팝업 마크업

## 재점검 이슈사항 
- [ ] : 비밀글 체크박스 (이미지 찌그러짐) 
- [ ] : table border 끊김
- [ ] : 팝업 상단 보더라인 레이아웃 조정 
- [ ] : 글자수카운트 p태그 재배치 
- [ ]
