### ISSUE TITLE
[Detail] 네비게이션바

### ISSUE THREAD

**Issue by SeoMiYoung** [likelion-lab8-JS/market-karly#25]
## 🌳 작업 브랜치
- page_productDetail_miyoung

## 📋 TASK 개요
- 디테일 파트의 네비게이션 부분을 완성합니다.

## ✅ To Do 및 진행상황
 - [x] 네비게이션 마크업
 - [x] 네비게이션 css
 - [x] 각 부분을 클릭하면 해당 정보로 화면 포커스 이동
 - [x] 후기옆에 후기 개수 넣기
 - [x] 후기가 증가하면 괄호안의 후기개수 증가하기 (동률님 코드 참고해서 작성)
 - [x] 네비게이션바의 해당 버튼을 클릭하면 버튼의 css 변화
 - [x] 네비게이션바를 스크롤로 내려도 항상 상단에 위치 고정시키기
