### ISSUE TITLE
[Detail] Description부분

### ISSUE THREAD

**Issue by SeoMiYoung** [likelion-lab8-JS/market-karly#27]
## 🌳 작업 브랜치
- page_productDetail_miyoung

## 📋 TASK 개요
- 디테일 파트의 상품설명 내용을 완성합니다

## ✅ To Do 및 진행상황
- [x] product_intro부분(상품설명의 첫부분) 마크업 
- [x] product_intro부분 css
- [x] Karly's Check Point 제목 마크업 + css
- [x] Karly's Check Point 내용 부분 마크업
- [x] Karly's Check Point 내용 부분 css
