### ISSUE TITLE
[Detail] 상세정보 부분 구현

### ISSUE THREAD

**Issue by SeoMiYoung** [likelion-lab8-JS/market-karly#30]
## 🌳 작업 브랜치
- page_productDetail_miyoung

## 📋 TASK 개요
- 디테일 파트의 상세정보 부분을 구현합니다

## ✅ To Do 및 진행상황
- [x] 상세정보에 대한 이미지 html + css
- [x] WHY KARLY 부분 마크업하기
- [x] WHY KARLY 부분 스타일하기
