### ISSUE TITLE
[main] 뷰티컬리 팝업창

### ISSUE THREAD

**Issue by jh1109** [likelion-lab8-JS/market-karly#32]
## 🌳 작업 브랜치
- page_main

## 📋 TASK 개요
- 뷰티컬리 팝업창 완성하기

## ✅ To Do 및 진행상황
- [x] 팝업창 마크업
- [x] 팝업창 디자인 및 레이아웃
- [x] 로드되었을 때 창이 뜨도록 하기
- [x] 닫기를 누르면 팝업창이 사라지는 기능 추가
