### ISSUE TITLE
[Detail] 선택한 상품개수에 따라 총 상품금액 변동하기

### ISSUE THREAD

**Issue by SeoMiYoung** [likelion-lab8-JS/market-karly#36]
## 🌳 작업 브랜치
- page_productDetail_miyoung

## 📋 TASK 개요
- 사용자가 +/-버튼을 눌러서 장바구니에 담을 수량을 결정하면, 그에 따라 상품개수가 변하고, 총 상품금액도 바뀝니다

## ✅ To Do 및 진행상황
- [x] +/-버튼 누를때마다 숫자 변동
- [x] 총 상품금액 변동
- [x] 수량이 1일때는 - 버튼 작동되지 않게 하기
- [x] 마이너스 버튼을 누르지 못할때는 cursor모양을 pointer말고, default로 설정
