### ISSUE TITLE
[productList] navigator 기능 구현

### ISSUE THREAD

**Issue by hayeonn2** [likelion-lab8-JS/market-karly#37]
## 🌳 작업 브랜치
padge_productList

## 📋 TASK 개요
상품 리스트 페이지에 있는 네비게이터 영역 기능을 구현합니다.

## ✅ To Do 및 진행상황
- [x] 아코디언 메뉴 작업하기
- [x] 카테고리 리스트 선택시 체크박스 활성화시키기
- [x] 체크박스 활성화 되면 초기화 버튼 활성화 시키기
