### ISSUE TITLE
[Detail] 네비게이션바 > 버튼을 누르면 해당 위치로 화면 초점 이동

### ISSUE THREAD

**Issue by SeoMiYoung** [likelion-lab8-JS/market-karly#40]
## 🌳 작업 브랜치
- page_productDetail_miyoung

## 📋 TASK 개요
- 사용자가 navigation에 있는 네개의 버튼(상품설명/상세정보/후기/문의) 중, 보고싶은 정보에 해당하는 버튼을 클릭하면, 해당 정보가 있는 곳으로 화면 초점이 이동합니다

## ✅ To Do 및 진행상황
- [x] 상품설명 버튼 이동 구현
- [x] 상세정보 버튼 이동 구현
- [x] 후기 버튼 이동 구현 (동률님과 코드 합친 후 진행)
- [x] 문의 버튼 이동 구현 (동률님과 코드 합친 후 진행)
