### ISSUE TITLE
[cart] 장바구니 페이지 마크업 및 기능 리팩토링

### ISSUE THREAD

**Issue by hayeonn2** [likelion-lab8-JS/market-karly#62]
## 🌳 작업 브랜치
page_cart

## 📋 TASK 개요
장바구니 페이지를 웹접근성에 맞춰 전반적인 마크업을 리팩토링하기
모듈함수를 사용해 기능을 다시 리팩토링하기

## ✅ To Do 및 진행상황
- [x] 장바구니 페이지에 들어갈 이미지 최적화
- [x] 라이트하우스를 사용해 접근성 및 성능향상을 위한 마크업 리팩토링
- [x] 모듈함수를 이용해 기능 리팩토링하기
- [x] 주석 제거하기
- [x] px -> rem 단위 변경
- [x] 명도대비 고려해 폰트 색상 변경
